---
- name: 'This playbook pushes a set of container images to the registry'
  hosts: registry
  vars_files:
    - vars/main.yml
  tasks:
    - name: 'Pull the container images'
      podman_image:
        name: "{{ item.name }}"
        tag: "{{ item.tag }}"
        username: "{{ registry_username }}"
        password: "{{ registry_password }}"
      loop:
        - name: "{{ ceph_image.name }}"
          tag: "{{ ceph_image.tag | default('latest') }}"
        - name: "{{ ceph_dashboard_image.name }}"
          tag: "{{ ceph_dashboard_image.tag | default('latest') }}"
