---
# This playbook requires the following variables defined:
# * rhcp_username
# * rhcp_password
# * ocp_version
# * registry_user
# * registry_password
# Execution $ ansible-playbook playbooks/00_setup_prerequisites.yaml -i inventory --ask-vault-pass

---
- name: Registry setup
  hosts: registry
  vars_files:
     - vars/main.yaml
     - vars/vault.yaml
  tasks:
    - name: Ensure prerequisites are met
      include_role:
        name: common
      tags: common

    - name: Setup registry
      include_role:
        name: registry
      when: inventory_hostname in groups['registry']
      tags: registry
